In [1]:
import numpy as np

In [9]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8 ]]) 
arr
print(arr.ndim)

2


In [4]:
print(arr.shape)

(2, 4)


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
print(arr.data)

In [10]:
arr.data


In [12]:
b=np.array([[1, 2, 3, 4], [6, 5, 7, 8],[2, 4, 4, 9]])
print(b,"\n")

[[1 2 3 4]
 [6 5 7 8]
 [2 4 4 9]] 



In [13]:
b.size

12

In [14]:
b.shape

(3, 4)

In [19]:
b=np.array([[1, 2, 3, 4], [6, 85, 7, 8],[25, 4, 64, 9]], dtype=np.float64)
print(b,"\n")
print(b.dtype,"\n")
print(b.itemsize)

[[ 1.  2.  3.  4.]
 [ 6. 85.  7.  8.]
 [25.  4. 64.  9.]] 

float64 

8


In [21]:
c=np.array([[1, 2, 3, 4], [6, 85, 7, 8],[25, 4, 64, 9]], dtype=np.complex64)
d=np.array([[1, 2, 3, 4], [6, 85, 7, 8],[25, 4, 64, 9]], dtype=np.complex128)
print(c,"\n")
print(c.dtype,"\n")
print(c.itemsize)
print(d,"\n")
print(d.dtype,"\n")
print(d.itemsize)

[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 6.+0.j 85.+0.j  7.+0.j  8.+0.j]
 [25.+0.j  4.+0.j 64.+0.j  9.+0.j]] 

complex64 

8
[[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j]
 [ 6.+0.j 85.+0.j  7.+0.j  8.+0.j]
 [25.+0.j  4.+0.j 64.+0.j  9.+0.j]] 

complex128 

16


In [22]:
print(np.sum(b))

218.0


In [23]:
print(b,"\n")
print(np.sum(b, axis=0)) #'0 it is represent column'
print(np.sum(b, axis=1))

[[ 1.  2.  3.  4.]
 [ 6. 85.  7.  8.]
 [25.  4. 64.  9.]] 

[32. 91. 74. 21.]
[ 10. 106. 102.]


In [28]:
b=np.array([[2, 4, 6], [6, 8, 2],[2, 4, 4]])
print(b,"\n")
print(np.amin(b))
print(np.amin(b, axis=0))
print(np.amin(b, axis=1))

[[2 4 6]
 [6 8 2]
 [2 4 4]] 

2
[2 4 2]
[2 2 2]


In [29]:
print(np.amax(b))
print(np.amax(b, axis=0))
print(np.amax(b, axis=1))
print(type(b))

8
[6 8 6]
[6 8 4]
<class 'numpy.ndarray'>


In [30]:
print(b,"\n")
print(np.mean(b))
print(np.mean(b, axis=0))
print(np.mean(b, axis=1))

[[2 4 6]
 [6 8 2]
 [2 4 4]] 

4.222222222222222
[3.33333333 5.33333333 4.        ]
[4.         5.33333333 3.33333333]


In [31]:
print(b,"\n")
print(np.median(b))
print(np.median(b, axis=0))
print(np.median(b, axis=1))

[[2 4 6]
 [6 8 2]
 [2 4 4]] 

4.0
[2. 4. 4.]
[4. 6. 4.]


In [32]:
print(b,"\n")
print(np.std(b))
print(np.std(b, axis=0))
print(np.std(b, axis=1))

[[2 4 6]
 [6 8 2]
 [2 4 4]] 

1.9876159799998132
[1.88561808 1.88561808 1.63299316]
[1.63299316 2.49443826 0.94280904]


In [33]:
#variance
print(b,"\n")
print(np.var(b))
print(np.var(b, axis=0))
print(np.var(b, axis=1))

[[2 4 6]
 [6 8 2]
 [2 4 4]] 

3.9506172839506175
[3.55555556 3.55555556 2.66666667]
[2.66666667 6.22222222 0.88888889]


In [34]:
#weighted averange
print(np.average(b))

4.222222222222222


In [35]:
E=np.array([1, 2, 3, 4, 5, 6, 7])
print(E)

[1 2 3 4 5 6 7]


In [36]:
W =np.array([0.23, 0.20, 0.21, 0.23, 0.24, 0.25,0.27])
print(W)

[0.23 0.2  0.21 0.23 0.24 0.25 0.27]


In [40]:
print(np.average(E,weights = W))
print(np.mean(E))

4.153374233128835
4.0


In [42]:
#percentile
print(b,"\n")
print(np.percentile(b, 5,0))
print(np.percentile(b, 3,0))
print(np.percentile(b, 4,0))


[[2 4 6]
 [6 8 2]
 [2 4 4]] 

[2.  4.  2.2]
[2.   4.   2.12]
[2.   4.   2.16]


In [44]:
print(b,"\n")
print(np.ptp(b, 0))
print(np.ptp(b, 1))
print(np.ptp(E, 0))

[[2 4 6]
 [6 8 2]
 [2 4 4]] 

[4 4 4]
[4 6 2]
6


In [53]:
p=np.array([[1, 2, 3, 4], [6, 5, 7, 8],[2, 4, 4, 9]])
print(p,"\n")
print(p.reshape(4, 3),"\n")
print(p,"\n")

[[1 2 3 4]
 [6 5 7 8]
 [2 4 4 9]] 

[[1 2 3]
 [4 6 5]
 [7 8 2]
 [4 4 9]] 

[[1 2 3 4]
 [6 5 7 8]
 [2 4 4 9]] 



In [50]:
l=np.array([[2, 4, 6, 6], [6, 8, 2, 8 ],[2, 4, 4, 7]])
print(l,"\n")
print(l[0,3],"\n")
print(l[1,2],"\n")
print(l[2,3],"\n")
print(l[0,1],"\n")
print(l[0:2,1],"\n")
print(l[-1],"\n")
print(l[-1,0:2],"\n")

[[2 4 6 6]
 [6 8 2 8]
 [2 4 4 7]] 

6 

2 

7 

4 

[4 8] 

[2 4 4 7] 

[2 4] 



In [62]:
M=np.arange(12).reshape(3,4)
print(M,'\n')
l=np.arange(12,24).reshape(3,4)
print(l)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [60]:
l=np.array([[2, 4, 6, 6], [6, 8, 2, 8 ],[2, 4, 4, 7]])
print(l,"\n")
print(M,"\n")
print(np.hstack((l,M)),'\n')
print(np.hstack((M,l)),'\n')

[[2 4 6 6]
 [6 8 2 8]
 [2 4 4 7]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 2  4  6  6  0  1  2  3]
 [ 6  8  2  8  4  5  6  7]
 [ 2  4  4  7  8  9 10 11]] 

[[ 0  1  2  3  2  4  6  6]
 [ 4  5  6  7  6  8  2  8]
 [ 8  9 10 11  2  4  4  7]] 



In [61]:
print(np.vstack((l,M)),'\n')
print(np.vstack((M,l)),'\n')

[[2 4 6 6]
 [6 8 2 8]
 [2 4 4 7]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 2  4  6  6]
 [ 6  8  2  8]
 [ 2  4  4  7]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 2  4  6  6]
 [ 6  8  2  8]
 [ 2  4  4  7]] 



In [64]:
from numpy import random

In [65]:
x= random.randint(100)
print(x)

77


In [68]:
x= random.rand()
print(x)

0.5092347430284055


In [70]:
x= random.randint(100, size=(3,4))
print(x)

[[49 62  2  1]
 [47 56 40 37]
 [42 52  0 54]]
